include:
- project: molsys/ci
  file: /ci/pipelines/molsys.bloodflow.yml
- project: hpc/gitlab-pipelines
  file: github-project-pipelines.gitlab-ci.yml
- project: hpc/gitlab-upload-logs
  file: enable-upload.yml

publish-package:
  needs: [build-wheels]
  stage: publish
  script:
    pip install twine
    python -m twine upload --username $PYPI_USER --password $PYPI_PASSWORD $PYTHON_PROJECT_DIR/wheelhouse
  rules:
  - if: $CI_COMMIT_TAG
