repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.0.0
    hooks:
        - id: commitlint
          stages:
            - commit-msg
          additional_dependencies: ['conventional-changelog-conventionalcommits']
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        args: ["-x", ".codespellignorelines"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.3.7
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format

  #- repo: https://github.com/PyCQA/pydocstyle
  #  rev: 6.1.1
  #  hooks:
  #    - id: pydocstyle
  #      additional_dependencies: ["toml"]
  #      exclude: 'examples|tests|scripts'
