name: Test the contribution
on:
  pull_request:
  push:
    branches:
    - main
env:
  apt_options: -o Acquire::Retries=3
  PETSC_DIR: /usr/lib/petscdir/petsc3.15/x86_64-linux-gnu-real
jobs:
  test:
    name: Build and test the contribution
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1
      with:
        mpi: openmpi
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install system packages
      run: |
        sudo apt-get ${{env.apt_options}} update -y
        sudo apt-get ${{env.apt_options}} install python3-petsc4py python3-mpi4py libopenmpi-dev libpetsc-real3.15-dev
    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install tox-gh-actions
    - name: Run tox
      run: tox
      #env:
      #  PYTHONPATH: ${{env.PETSC_DIR}}/lib/python3/dist-packages
